variables:
  # Required. Adjust to match your project:
  GROUP_NAME: ""
  PROJECT_NAME: ""

release:
  stage: deploy
  allow_failure: false
  image: wemakeservices/kira-release:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
    REGISTRY: "registry.gitlab.com"
    # Uncomment to skip gitlab docker registry releases:
    # KIRA_RELEASE_SKIP_DOCKER: 'true'
  script:
    # Build local image to be released to gitlab registry,
    # modify it to suite your needs as you wish.
    # We only care about the name of the image:
    - docker build -t "$REGISTRY/$GROUP_NAME/$PROJECT_NAME" .
    # Release everything!
    - npm run release
  only:
    - master
  # Uncomment to make the release process manual:
  # when: manual
