---

language: node_js

node_js:
  - 10

before_script:
  - git config --global user.name 'Kira Bot'
  - git config --global user.email 'kira@wemake.services'

install:
  - yarn install

script:
  - yarn test

notifications:
  email:
    on_success: never
    on_failure: change
