name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: build docker image
      run: docker build . --tag=wemake-services/kira-release

    - name: run docker-based test
      run: |
        docker run \
          -e KIRA_RELEASE_SKIP_DOCKER=true \
          -e KIRA_RELEASE_REPLACE_CONFIG='{ "project": "package.json", "from": "\"version\": \".*\"", "to": "\"version\": \"${nextRelease.version}\"" }' \
          wemake-services/kira-release \
          semantic-release --dry-run
