name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: build docker image
      run: docker build . --tag=wemake-services/kira-release

    - name: run docker-based test
      run: |
        docker run \
          -e KIRA_RELEASE_SKIP_DOCKER=true \
          -e KIRA_RELEASE_REPLACE_CONFIG='{ "project": "package.json", "from": "\"version\": \".*\"", "to": "\"version\": \"${nextRelease.version}\"" }' \
          -v $PWD/tests:/tests \
          wemake-services/kira-release \
          sh /tests/run.sh
